apiVersion: v1
kind: Template
metadata:
  name: build-plotinfo-service
  annotations:
    openshift.io/display-name: "Buildconfig for plotinfo-service"
    description: >-
      "Creates BuildConfig for plotinfo-service"
parameters:
  - description: tag of base image
    name: BASETAG
  - description: tag of deploy image
    name: DEPLOYTAG
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      service: plotinfo-service
      app: gdi
    name: plotinfo-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: plotinfo-service:${DEPLOYTAG}
    source:
      contextDir: plotinfo-service
      git:
        ref: master
        uri: https://github.com/sogis/qwc_services.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: sourcepole/sogis-plotinfo-service:${BASETAG}
        noCache: true
      type: Docker
    resources:
      limits:
        cpu: "1000m"
        memory: "4096Mi"
      requests:
        cpu: "250m"
        memory: "1024Mi"
