apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ressources-qgis-server
  annotations:
    description: >-
      "Creates necessary ressources for qgis-server"
parameters:
  - description: DB Server Url
    name: DB_SERVER
  - description: Geo DB Server
    name: GEO_DB_SERVER
  - description: Pub DB
    name: DB_PUB
  - description: Edit DB
    name: DB_EDIT
  - description: Oereb DB
    name: DB_OEREB
  - description: Sogis DB
    name: DB_SOGIS
  - description: DB User ogc_server
    name: USER_OGC_SERVER
  - description: Password DB User ogc_server
    name: PW_OGC_SERVER
objects:
- apiVersion: v1
  stringData:
    pg_service.conf: |
      [sogis_pub]
      host=${DB_SERVER}
      port=5432
      dbname=${DB_PUB}
      user=${USER_OGC_SERVER}
      password=${PW_OGC_SERVER}
      sslmode=require

      [sogis_geodb]
      host=${GEO_DB_SERVER}
      port=5432
      dbname=${DB_SOGIS}
      user=mspublic
      sslmode=disable

      [sogis_edit]
      host=${DB_SERVER}
      port=5432
      dbname=${DB_EDIT}
      user=${USER_OGC_SERVER}
      password=${PW_OGC_SERVER}
      sslmode=require

      [sogis_oereb]
      host=${DB_SERVER}
      port=5432
      dbname=${DB_OEREB}
      user=${USER_OGC_SERVER}
      password=${PW_OGC_SERVER}
      sslmode=require
  kind: Secret
  metadata:
    labels:
      app: gdi
      service: qgis-server
    name: qgis-server-pg-service-secret
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: qgis-server
      app: gdi
    name: qgis-server
  spec:
    ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: qgis-server
