apiVersion: v1
kind: Template
metadata:
  name: build-landreg-service
  annotations:
    openshift.io/display-name: "Buildconfig for landreg-service"
    description: >-
      "Creates BuildConfig for landreg-service"
parameters:
  - description: tag of base image
    name: BASETAG
  - description: tag of deploy image
    name: DEPLOYTAG
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      service: landreg-service
      app: gdi
    name: landreg-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: landreg-service:${DEPLOYTAG}
    source:
      contextDir: landreg-service
      git:
        ref: master
        uri: https://github.com/sogis/qwc_services.git
      sourceSecret:
        name: deployso-at-gitlab
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: sourcepole/sogis-landreg-service:${BASETAG}
        noCache: true
      type: Docker
    resources:
      limits:
        cpu: "1000m"
        memory: "4096Mi"
      requests:
        cpu: "250m"
        memory: "1024Mi"
