apiVersion: v1
kind: Template
metadata:
  name: build-jasper-reporting-service
  annotations:
    openshift.io/display-name: "Buildconfig for jasper-reporting-service"
    description: >-
      "Creates BuildConfig for jasper-reporting-service"
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: jasper-reporting-service
    name: jasper-reporting-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jasper-reporting-service:latest
    source:
      contextDir: docker/jasper-reporting-service
      git:
        ref: release_so
        uri: https://git.sourcepole.ch/ktso/somap.git
      sourceSecret:
        name: deployso-at-gitlab
      type: Git
    strategy:
      dockerStrategy:
        buildArgs:
        - name: GIT_VERSION
          value: v2.0.8
        env:
        - name: GIT_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: deployso-at-gitlab
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: deployso-at-gitlab
        from:
          kind: DockerImage
          name: openjdk:9
      type: Docker
