apiVersion: v1
kind: Template
metadata:
  name: build-jasper-reporting-service
  annotations:
    openshift.io/display-name: "Buildconfig for jasper-reporting-service"
    description: >-
      "Creates BuildConfig for jasper-reporting-service"
parameters:
  - description: branch to build
    name: BRANCH
    value:
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      service: jasper-reporting-service
      app: gdi
    name: jasper-reporting-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jasper-reporting-service:latest
    source:
      contextDir: docker/jasper-reporting-service
      git:
        ref: ${BRANCH}
        uri: https://git.sourcepole.ch/ktso/somap.git
      sourceSecret:
        name: deployso-at-gitlab
      type: Git
    strategy:
      dockerStrategy:
        buildArgs:
        - name: JASPER_REPORTING_VERSION
          value:
        from:
          kind: DockerImage
          name: openjdk:9
      type: Docker
