apiVersion: v1
kind: Template
metadata:
  name: jasper-reporting-service
  annotations:
    description: "Creates deploymentConfig for jasper-reporting-service"
parameters:
  - description: Openshift Namespace
    name: NAMESPACE
  - description: "Image Stream Tag"
    name: TAG
  - description: 'Number of Replicas'
    name: REPLICAS
labels:
  application: gdi
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kompose.cmd: kompose --file docker-compose-4openshift.yml --provider openshift
        convert
      kompose.version: 1.10.0 (8bb0907)
    labels:
      service: jasper-reporting-service
      app: gdi
    name: jasper-reporting-service
  spec:
    replicas: ${{REPLICAS}}
    selector:
      service: jasper-reporting-service
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 120
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          service: jasper-reporting-service
          app: gdi
      spec:
        containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JASPER_REPORTING_SERVICE
              value: 0.5.1
          image: docker-registry.default.svc:5000/${NAMESPACE}/jasper-reporting-service:${TAG}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: >-
                /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: sogis-jasper-reporting-service
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: >-
                /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /srv/jasper-reporting-service/reports
            name: reports
            readOnly: true
          - mountPath: /srv/jasper-reporting-service/config
            name: jasper-config-claim
            readOnly: true
          - mountPath: /etc/postgresql-common
            name: jasper-reporting-service-config-claim
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - secret:
            items:
            - key: pg_service.conf
              path: pg_service.conf
            secretName: jasper-reporting-service-pg-config
          name: jasper-reporting-service-config-claim
        - name: reports
          persistentVolumeClaim:
            claimName: reports-claim
            readOnly: true
        - secret:
            items:
            - key: application.properties
              path: application.properties
            secretName: jasper-config
          name: jasper-config-claim
    test: false
    triggers: []
