def serviceName = 'jasper-reporting-service'
def repo = 'https://raw.githubusercontent.com/sogis/pipelines/master/api_webgisclient/' + serviceName
// NOTE, the "pipeline" directive/closure from the declarative pipeline syntax needs to include, or be nested outside,
// and "openshift" directive/closure from the OpenShift Client Plugin for Jenkins.  Otherwise, the declarative pipeline engine
// will not be fully engaged.
println(env.NAMESPACE_JENKINS)
println(env.EDIT_DB)

library identifier: 'jenkins-shared-libs@master', retriever: modernSCM(
    [$class: 'GitSCMSource',
     remote: 'https://github.com/sogis/jenkins-shared-libs.git'])

pipeline {
    agent { label 'master' } 
    environment {
      CREDENTIALS = withCredentials([
          usernamePassword(credentialsId: 'agi-apps-integration-pw-mswrite'             , usernameVariable: 'DbUserMswrite'           , passwordVariable: 'PwdMswrite'),
         // usernamePassword(credentialsId: (env.NAMESPACE) + '-pw-mswrite'             , usernameVariable: 'DbUserMswrite'           , passwordVariable: 'PwdMswrite'),
          usernamePassword(credentialsId: (env.NAMESPACE_JENKINS) + '-pw-report-server'       , usernameVariable: 'DbUserReportServer'      , passwordVariable: 'PwdReportServer'),
         // usernamePassword(credentialsId: (env.NAMESPACE) + '-pw-sogis-service'       , usernameVariable: 'DbUserSogisService'      , passwordVariable: 'PwdSogisService'),        // usernamePassword(credentialsId: (env.NAMESPACE) + '-pw-imdas-db-user'       , usernameVariable: 'DbUserImdasDb'           , passwordVariable: 'PwdImdasUser'),
      ])
    }
    options {
        // set a timeout of 10 minutes for this pipeline
        timeout(time: 10, unit: 'MINUTES')
        }
    parameters {
        string(defaultValue: "v2.0.8",
               description: 'Basis Image Version',
               name: 'vBaseImage' 
               )
        string(description: 'Tag des generierten bzw. deployten Images',
               name: 'vDeployImage'
               )
        string(description: 'Anzahl der Replicas',
               defaultValue: '1',
               name: 'replicas'
               )
        string(defaultValue: "gdi-test",
               description: 'Bitte namespace auswählen',
               name: 'namespace'
               )
        }

    stages {
        stage ('Ask for Version') {
            steps {
                script {
                    vBaseImage = params.vBaseImage
                    vDeployImage = params.vDeployImage
                    replicas = params.replicas
                    namespace = params.namespace
                    }
                }
            }
        stage ('Configure Ressources') {
            steps {
                withCredentials ( CREDENTIALS ) {
                    println(env.NAMESPACE_JENKINS)
                    println(env.EDIT_DB)
                    configureRessources '${namespace}', "-f ${repo}/resources.yaml -p DB_SERVER=geodb-t.rootso.org -p GEO_DB_SERVER=geodb-t.verw.rootso.org -p IMDAS_DB_SERVER=srsofaioi18943.verw.rootso.org -p DB_PUB=${env.PUB_DB} -p DB_EDIT=${env.EDIT_DB} -p DB_CONFIG=${env.CONFIG_DB} -p DB_SOGIS=${env.SOGIS_DB} -p DB_IMDAS=${env.IMDAS_DB} -p USER_SOGIS_SERVICE=${DbUserSogisService} -p PW_SOGIS_SERVICE=${PwdSogisService} -p USER_REPORT_SERVER=${DbUserReportServer} -p PW_REPORT_SERVER=${PwdReportServer} -p USER_MSWRITE=${DbUserMswrite} -p PW_MSWRITE=${PwdMswrite} -p USER_IMDAS_DB=${DbUserImdasDb} -p PW_IMDAS_DB_USER=${PwdImdasUser} -p NAMESPACE=${namespace}"
                    }
                }
             }
        stage ( 'Tag Image in Openshift' ) {
            steps {
                script {
                    sh """
                       oc tag -n $namespace --source=docker sogis/jasper-reporting-service:$vBaseImage jasper-reporting-service:$vDeployImage
                    """
                    }
                }
            }
        stage ( 'Deploy jasper-reporting-service' ) {
            steps {
                deployImage serviceName, namespace, vDeployImage, repo, replicas
                }
            }
        }
    }
