apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ressources-legend-service
  annotations:
    description: >-
      "Creates necessary ressources for legend-service"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose --file docker-compose-4openshift.yml --provider openshift
        up
      kompose.version: 1.10.0 (8bb0907)
    labels:
      service: legend-service
      app: gdi
    name: legend-service
  spec:
    ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 9090
    selector:
      service: legend-service
    sessionAffinity: None
    type: ClusterIP
