apiVersion: v1
kind: Template
metadata:
  name: qwc-service
  annotations:
    description: "Creates deploymentConfig for qwc-service"
parameters:
  - description: Openshift Namespace
    name: NAMESPACE
    value:
  - description: Image Stream Tag
    name: TAG
labels:
  application: gdi
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: qwc-service
      app: gdi
    name: qwc-service
  spec:
    replicas: 2
    selector:
      service: qwc-service
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 120
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          service: qwc-service
          app: gdi
      spec:
        containers:
        - env:
          - name: AUTH_SERVICE_URL
            value: /auth/
          - name: DATA_SERVICE_URL
            value: /api/data/v1/
          - name: ELEVATION_SERVICE_URL
            value: /elevation/
          - name: INFO_SERVICE_URL
            value: /api/v1/featureinfo/
          - name: LEGEND_SERVICE_URL
            value: /api/v1/legend/
          - name: MAPINFO_SERVICE_URL
            value: /api/v1/mapinfo/
          - name: FEATURE_REPORT_SERVICE_URL
            value: /api/v1/document/
          - name: PERMALINK_SERVICE_URL
            value: /api/v1/permalink/
          - name: PRINT_SERVICE_URL
            value: /api/v1/print/
          - name: QGIS_SERVER_URL
            value: /ows/
          - name: SEARCH_SERVICE_URL
            value: /api/search/v2/fts/
          - name: SEARCH_DATA_SERVICE_URL
            value: /api/data/v1/
          - name: JWT_SECRET_KEY
            value: fce9dd0cc67ae26c7b2fb912e31a4657e99014e50ccb90bd
          - name: ALLOW_BASIC_AUTH_USER
            value: "True"
          - name: WMS_DPI
            value: "96"
          - name: DATAPRODUCT_SERVICE_URL
            value: /api/dataproduct/v1/
          - name: MIN_RESULTS_EXANDED
            value: "100"
          - name: SERVICE_MOUNTPOINT
            value: /map
          - name: CONFIG_PATH
            value: /srv/qwc_service/config
          image: docker-registry.default.svc:5000/${NAMESPACE}/qwc-service:${TAG}
          imagePullPolicy: IfNotPresent
          name: sogis-qwc-service
          ports:
          - containerPort: 9090
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /srv/somap/qwc_service/templates
            name: config-json-claim
          - mountPath: /var/www
            name: qwc-service-config-claim
          - mountPath: /srv/somap/qwc_service/qwc2/assets/img/custommapthumbs
            name: qwc-assets
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - secret:
            items:
            - key: pg_service.conf
              path: .pg_service.conf
            secretName: qwc-service-pg-config
          name: qwc-service-config-claim
        - configMap:
            defaultMode: 420
            items:
              - key: config.json
                path: config.json
            name: config-json
          name: config-json-claim
        - name: qwc-assets
          persistentVolumeClaim:
            claimName: qwc-assets-claim
            readOnly: true
    triggers: []
