kind: BuildConfig
apiVersion: v1
metadata:
  name: api-gateway
spec:
  source:
    git:
      uri: "https://github.com/sogis/pipelines.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: api_webgisclient/api-gateway/Jenkinsfile
