apiVersion: v1
kind: Template
metadata:
  name: build-api-gateway
  annotations:
    openshift.io/display-name: "Buildconfig for data-service"
    description: >-
      "Creates BuildConfig for data-service"
parameters:
  - description: tag of deploy image
    name: DEPLOYTAG
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      service: api-gateway
      app: gdi
    name: api-gateway
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: api-gateway:${DEPLOYTAG}
    source:
      contextDir: api-gateway
      git:
        ref: master
        uri: https://github.com/sogis/qwc_services.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: nginx:mainline-alpine
        noCache: false
      type: Docker
    resources:
      limits:
        cpu: "1000m"
        memory: "4096Mi"
      requests:
        cpu: "250m"
        memory: "1024Mi"
