apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: build-api-gateway
  annotations:
    openshift.io/display-name: "Buildconfig for data-service"
    description: >-
      "Creates BuildConfig for data-service"
parameters:
  - description: tag of deploy image
    name: DEPLOYTAG
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      service: api-gateway
      app: gdi
    name: api-gateway
  spec:
    successfulBuildsHistoryLimit: 1
    failedBuildsHistoryLimit: 2
    output:
      to:
        kind: ImageStreamTag
        name: api-gateway:${DEPLOYTAG}
    source:
      contextDir: api-gateway
      git:
        ref: amplify
        uri: https://github.com/sogis/qwc_services.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: nginxinc/nginx-unprivileged:mainline
        noCache: false
        pullSecret:
          name: sogis-pull-secret
      type: Docker
    resources:
      limits:
        cpu: "1000m"
        memory: "4096Mi"
      requests:
        cpu: "250m"
        memory: "1024Mi"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      service: filebeat
      app: gdi
    name: filebeat
  spec:
    successfulBuildsHistoryLimit: 1
    failedBuildsHistoryLimit: 2
    output:
      to:
        kind: ImageStreamTag
        name: filebeat:${DEPLOYTAG}
    source:
      contextDir: filebeat
      git:
        ref: amplify
        uri: https://github.com/sogis/qwc_services.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: debian:11
        noCache: false
        pullSecret:
          name: sogis-pull-secret
      type: Docker
    resources:
      limits:
        cpu: "1000m"
        memory: "4096Mi"
      requests:
        cpu: "250m"
        memory: "1024Mi"
