apiVersion: v1
kind: Template
metadata:
  name: ressources-qwc-service
  annotations:
    description: >-
      "Creates necessary ressources for qwc-service"
parameters:
  - description: Namespace
    name: NAMESPACE
  - description: GDI Environment
    name: ENVIRONMENT
  - description: URL for GDI Environment
    name: BASEURL
  - description: WMTS URL
    name: WMTS_URL
  - description: Matomo URL
    name: MATOMO_URL
  - description: Url with no SES
    name: NO_SES_URL
objects:
- apiVersion: v1
  data:
    nginx_base_os.conf: |
      #user  nginx;
      worker_processes  auto;
      
      error_log  /var/log/nginx/error.log warn;
      pid        /var/run/nginx.pid;
      
      
      events {
          worker_connections  1024;
      }
      
      
      http {
          include       /etc/nginx/mime.types;
          default_type  application/octet-stream;
      
          log_format  main  '[$time_local] $http_hsp_client_addr "$http_x_forwarded_for" - $status "$request" - '
                            '$body_bytes_sent "$http_user_agent $remote_user'
                            'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time" $upstream_cache_status $upstream_addr';
      
          access_log  /var/log/nginx/access.log  main;
      
          sendfile        on;
          #tcp_nopush     on;
      
          keepalive_timeout  65;

          #gzip on;

          include /etc/nginx/conf.d/*.conf;
      }
  kind: ConfigMap
  metadata:
    name: nginx-base-config
    labels:
      service: api-gateway
      app: gdi
- apiVersion: v1
  data:
    nginx_os.conf: |
      server {
        listen 8081 ssl;
        server_name  localhost;
        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        
        underscores_in_headers on;

        proxy_redirect     off;
        proxy_set_header   Host              $http_host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $http_hsp_client_addr;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_connect_timeout       1200;
        proxy_send_timeout          1200;
        proxy_read_timeout          1200;
        send_timeout                1200;

        proxy_buffer_size 512k;
        proxy_buffers 8 512k;
        proxy_busy_buffers_size 512k;
        proxy_temp_file_write_size 512k;
        client_max_body_size 50M;

        add_header 'Access-Control-Allow-Origin' '*';

        location /nginx_status {
            stub_status on;
            access_log  on;
        }

        location / {
            # If st is a coordinate and c exists set hc=1 and remove st
            if ($args ~ ^(.+&|)st(=[0-9%C,]+)(.*)(c=[0-9%C,]+)(&s=[0-9]+)$) {
              return 301 "$uri?$1hc=1$3$4$5";
            }
            # If st is a coordinate and c doesnt exist set hc=1, set c=st and remove st (case Imdas Pro)
            if ($args ~ ^(.+&|)st(=[0-9%C,]+)(.*)$) {
              return 301 "$uri?$1hc=1$3&c$2&s=250";
            }
            proxy_pass http://qwc-service.${NAMESPACE}.svc;
        }

        location ~ /map/grundstuecksinformation {
            rewrite ^/map/grundstuecksinformation$ /map?realty= break;
            proxy_pass http://qwc-service.${NAMESPACE}.svc;
        }
        location ~ /map/kbs {
            rewrite ^/map/kbs$ /map?k=3eb2c19b4 break;
            proxy_pass http://qwc-service.${NAMESPACE}.svc;
        }

        location ~ /map/([a-z_]+) {
            rewrite ^/map/([a-z_]+)$ /map?t=$1 break;
            proxy_pass http://qwc-service.${NAMESPACE}.svc;
        }

        location ~ ^/docs/(ch\.so\.arp\.nutzungsvereinbarungen|ch\.so\.awjf\.biotopbaeume)/(.*)$ {
            set $url1 $1; 
            set $url2 $2;
            if ($http_hsp_client_addr !~ ^10\.36\.([0-9]+)(.*)([0-9]+)$) { 
                return 403;
            }
            alias /geodata/documents/$url1/$url2;
            autoindex off;
        }

        location ~ ^/docs/(ch\.so\.alw\.strukturverbesserungen\/nicht_oeffentlich)/(.*)$ {
            set $url1 $1; 
            set $url2 $2;
            if ($http_hsp_client_addr !~ ^10\.36\.([0-9]+)(.*)([0-9]+)$) { 
                return 403;
            }
            alias /geodata/documents/$url1/$url2;
            autoindex on;
        }

        location /docs {
            alias /geodata/documents;
            autoindex on;
        }

        location ~ /geodata/ch.swisstopo.lk(.*) {
            allow 193.135.87.0/24;
            deny all;
        }

        location ~ ^/geodata/ch.so.agi.lidar_2019.ept/(ept-data)/(.*)$ {
            alias /geodata/geodata/ch.so.agi.lidar_2019.ept/$1/$2;
            autoindex off;
        }

        location /geodata {
            alias /geodata/geodata;
            autoindex on;
        }

        location /auth/ {
            proxy_pass http://auth-service.${NAMESPACE}.svc;
        }

        location /ows {
            proxy_pass http://ogc-service.${NAMESPACE}.svc;
        }

        location /wms {
            proxy_pass http://ogc-service.${NAMESPACE}.svc/ows/somap;
        }
        location /api/wms {
            proxy_pass http://ogc-service.${NAMESPACE}.svc/ows/somap;
        }

        location /api/wmsauth {
            proxy_pass http://ogc-service.${NAMESPACE}.svc/ows/somap;
            proxy_set_header Authorization "Basic d21zYXV0aDpwYXNzd29yZAo=";
        }

        location /wfs {
            proxy_pass http://ogc-service.${NAMESPACE}.svc/ows/somap;
        }

        location /api/wfs {
            proxy_pass http://ogc-service.${NAMESPACE}.svc/ows/somap;
        }

        location /api/v1/permalink {
            proxy_pass http://permalink-service.${NAMESPACE}.svc;
        }

        location /elevation {
            proxy_pass http://elevation-service.${NAMESPACE}.svc;
        }

        location /api/search/v2 {
            proxy_pass http://search-service.${NAMESPACE}.svc;
        }

        location /api/data/v1 {
            proxy_pass http://data-service.${NAMESPACE}.svc;
        }

        location /api/dataproduct/v1 {
            proxy_pass http://dataproduct-service.${NAMESPACE}.svc;
        }
        location /api/v1/mapinfo {
            proxy_pass http://mapinfo-service.${NAMESPACE}.svc;
        }

        location /api/oereb {
            proxy_set_header 'X-FORWARDED-HOST' '${BASEURL}';
            proxy_set_header 'X-FORWARDED-PREFIX' '/api/oereb';
            proxy_set_header 'X-FORWARDED-PROTO' 'https';
            proxy_pass http://oereb-web-service.agi-oereb-${ENVIRONMENT}.svc/;
        }

        location /api/v1/plotinfo {
            proxy_pass http://plotinfo-service.${NAMESPACE}.svc;
        }

        location /api/v1/print {
            proxy_pass http://print-service.${NAMESPACE}.svc;
        }

        location /api/v1/legend {
            proxy_pass http://legend-service.${NAMESPACE}.svc;
        }

        location /api/v1/featureinfo {
            proxy_pass http://featureinfo-service.${NAMESPACE}.svc;
        }

        location /api/v1/ccc {
            proxy_pass http://ccc-config.${NAMESPACE}.svc/api/v1/ccc;
        }

        location /api/v1/document {
            proxy_pass http://document-service.${NAMESPACE}.svc;
        }

        location /agdi {
            proxy_pass http://agdi.${NAMESPACE}.svc;
        }

        location /api/v1/landreg {
            proxy_pass http://landreg-service.${NAMESPACE}.svc;
        }
        location /api/wms-cache/ {
            proxy_pass http://${WMTS_URL}/mapcache/;
            proxy_set_header Host       $proxy_host;
        }

        location /api/wmts/ {
            proxy_pass http://${WMTS_URL}/mapcache/wmts/;
            proxy_set_header Host       $proxy_host;
        }

        location /wms/oereb {
            proxy_pass http://oereb-wms.agi-oereb-${ENVIRONMENT}.svc; 
        }
      
        location /wms/oereb-symbols {
            proxy_pass http://oereb-wms.agi-oereb-${ENVIRONMENT}.svc; 
        }
        
        location /gb2av {
            proxy_pass http://gb2av.agi-apps-${ENVIRONMENT}.svc/;
        }

        location /ilivalidator {
            proxy_set_header   X-Forwarded-For $remote_addr;
            proxy_set_header   Host $http_host;
            proxy_pass http://ilivalidator-service.agi-apps-${ENVIRONMENT}.svc/ilivalidator/; 
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
        }

        location /ili2gpkg {
            proxy_set_header   X-Forwarded-For $remote_addr;
            proxy_set_header   Host $http_host;
            proxy_pass http://ili2gpkg-web-service.agi-apps-${ENVIRONMENT}.svc/;  
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection "upgrade";
        }
        
        location /av_datenabgabe/ {
            proxy_pass http://cadastral-data-disposal.agi-apps-${ENVIRONMENT}.svc;
        }

        location /avgbs2mtab {
            proxy_pass http://avgbs2mtab-service.agi-apps-${ENVIRONMENT}.svc/avgbs2mtab/;
        }

        location /ews {
            proxy_pass http://heatdrill-service.agi-apps-${ENVIRONMENT}.svc/service/;
        }

        location /lidar-browser {
            proxy_pass http://lidar-browser.agi-apps-${ENVIRONMENT}.svc/;
        }

        location /standortkarte/ {
            proxy_pass http://standortkarte.agi-apps-${ENVIRONMENT}.svc/;
        }

        location /models {
            proxy_pass http://interlis-repository.agi-apps-${ENVIRONMENT}.svc/;
        }

        #location /api/cadastre/v1 {
        #    proxy_pass http://cadastre-web-service.agi-apps-test.svc/;
        #} 

        location /api/embed/v1 {
            proxy_pass http://wgc-embedded.agi-apps-${ENVIRONMENT}.svc/; 
        }

        # For Statuscake Tests
        location /indexupdater {
            proxy_pass http://indexupdater.solr-cloud-${ENVIRONMENT}.svc/status;
        }
        location /apidoc.html {
            root   /usr/share/nginx/html;
        }

        location /analytics {
            proxy_set_header 'X-FORWARDED-HOST' '${BASEURL}';
            proxy_set_header 'X-FORWARDED-PREFIX' '/analytics';
            proxy_set_header 'X-FORWARDED-PROTO' 'https';
            proxy_pass http://${MATOMO_URL}/;
        }

        #error_page  404   /404.html;
        #location = /404.html {
        #    root   /usr/share/nginx/html;
        #}

        # redirect server error pages to the static page /50x.html
        #
        #error_page   500 502 503 504  /maintenance.html;
        error_page   500 502 503 504  /50x.html;
        #location = /maintenance.html {
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
      }
  kind: ConfigMap
  metadata:
    name: nginx-config
    labels:
      service: api-gateway
      app: gdi
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: api-gateway
    labels:
      app: gdi
      service: api-gateway
  spec:
    tags:
      - name: latest
        from:
          kind: DockerImage
          name: 'docker-registry.default.svc:5000/${NAMESPACE}/api-gateway:latest'
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: api-gateway-cert
    labels:
      app: gdi
      service: api-gateway
    name: api-gateway
  spec:
    ports:
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 8081
    selector:
      service: api-gateway
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: gdi
      service: api-gateway
    name: api-gateway
  spec:
    host: ${BASEURL}
    port:
      targetPort: 443-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: reencrypt
    to:
      kind: Service
      name: api-gateway
      weight: 100
    wildcardPolicy: None
  status:
    ingress: null
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: gdi
      service: api-gateway
    annotations:
      openshift.io/long-description: >-
        "Route Necessary for Autologin check. Checks if user comes from intra- or internet. If user comes from intranet Single Sign On is used"
    name: api-gateway-ohne-ses
  spec:
    host: ${NO_SES_URL}.dev.so.ch
    port:
      targetPort: 443-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: reencrypt
    to:
      kind: Service
      name: api-gateway
      weight: 100
    wildcardPolicy: None
