apiVersion: v1
kind: Template
metadata:
  name: build-qgis-server
  annotations:
    openshift.io/display-name: "Buildconfig for qgis-server"
    description: >-
      "Creates BuildConfig for qgis-server"
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: qgis-server
    name: qgis-server
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: qgis-server:latest
    source:
      contextDir: docker/qgis-server
      git:
        ref: release_so
        uri: https://git.sourcepole.ch/ktso/somap.git
      sourceSecret:
        name: deployso-at-gitlab
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: phusion/baseimage:0.10.0
      type: Docker
