apiVersion: v1
kind: Template
metadata:
  name: qgis-server
  annotations:
    description: "Creates deploymentConfig for qgis-server"
parameters:
  - description: Openshift Namespace
    name: NAMESPACE
    value:
labels:
  application: gdi
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    generation: 1
    labels:
      app: qgis-server
    name: qgis-server
  spec:
    replicas: 2
    selector:
      app: qgis-server
      deploymentconfig: qgis-server
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 120
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        labels:
          app: qgis-server
          deploymentconfig: qgis-server
      spec:
        containers:
        - env:
          - name: LOG_LEVEL
            value: 2
          - name: QGIS_FCGI_MIN_PROCESSES
            value: 2
          - name: QGIS_FCGI_MAX_PROCESSES
            value: 2
          image: docker-registry.default.svc:5000/${NAMESPACE}/qgis-server
          imagePullPolicy: Always
          name: sogis-qgis-server
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 10Gi
            requests:
              cpu: '4'
              memory: 10Gi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /data
            name: qgs-resources
          - mountPath: /geodata
            name: datensogispicmir
          - mountPath: /etc/postgresql-common
            name: qgis-server-config-claim
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: pg_service.conf
              path: pg_service.conf
            name: qgis-server-pg-config
          name: qgis-server-config-claim
        - name: qgs-resources
          persistentVolumeClaim:
            claimName: qgs-resources-claim
        - name: datensogispicmir
          persistentVolumeClaim:
            claimName: datensogispicmir-claim1
            readOnly: true
    test: false
    triggers:
    - type: ConfigChange
