apiVersion: v1
kind: Template
metadata:
  name: qgis-server
  annotations:
    description: "Creates deploymentConfig for qgis-server"
parameters:
  - description: Openshift Namespace
    name: NAMESPACE
  - description: Image Stream Tag
    name: TAG
  - description: Environment
    name: ENVIRONMENT
labels:
  application: gdi
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    generation: 1
    labels:
      service: qgis-server
      app: gdi
    name: qgis-server
  spec:
    replicas: 1
    selector:
      service: qgis-server
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 120
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        labels:
          service: qgis-server
          app: gdi
      spec:
        containers:
        - env:
          - name: LOG_LEVEL
            value: "2"
          - name: QGIS_FCGI_MIN_PROCESSES
            value: "2"
          - name: QGIS_FCGI_MAX_PROCESSES
            value: "2"
          image: docker-registry.default.svc:5000/${NAMESPACE}/qgis-server:${TAG}
          imagePullPolicy: Always
          name: sogis-qgis-server
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /data/symbols
            name: qgs-resources
            subPath: symbols
          - mountPath: /data/print
            name: qgs-resources
            subPath: print
          - mountPath: /geodata
            name: datensogispicmir
          - mountPath: /etc/postgresql-common
            name: qgis-server-config-claim
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - secret:
            items:
            - key: pg_service.conf
              path: pg_service.conf
            secretName: qgis-server-pg-config
          name: qgis-server-config-claim
        - name: qgs-resources
          persistentVolumeClaim:
            claimName: qgs-resources-claim
        - name: datensogispicmir
          persistentVolumeClaim:
            claimName: datensogispicmir-claim-${ENVIRONMENT}
    test: false
    triggers: []
