def serviceName = 'qgis-server'
def repo = 'https://raw.githubusercontent.com/sogis/pipelines/master/api_webgisclient/' + serviceName
def namespace = 'gdi-devel'
// NOTE, the "pipeline" directive/closure from the declarative pipeline syntax needs to include, or be nested outside,
// and "openshift" directive/closure from the OpenShift Client Plugin for Jenkins.  Otherwise, the declarative pipeline engine
// will not be fully engaged.
credentials = [
    usernamePassword(credentialsId: 'agi-apps-test-pw-ogc-server'          , usernameVariable: 'DbUserOgcServer'         , passwordVariable: 'PwdOgcServer'),
]
library identifier: 'jenkins-shared-libs@master', retriever: modernSCM(
    [$class: 'GitSCMSource',
     remote: 'https://github.com/sogis/jenkins-shared-libs.git'])

pipeline {
    agent any 
    options {
        // set a timeout of 10 minutes for this pipeline
        timeout(time: 10, unit: 'MINUTES')
        }
    parameters {
        string(description: 'Bitte Tag des generierten bzw. deployten Images angeben',
               name: 'vDeployImage'
               )
        string(defaultValue: "gdi-test",
               description: 'Bitte namespace auswählen',
               name: 'namespace'
               )
        string(defaultValue: "release_so",
               description: 'Bitte Branch auswählen',
               name: 'branch'
               )
        choice(choices: ['ja','nein'],
               description: 'Soll das Image gebaut werden?',
               name: 'build'     
               )
        }

    stages {
        stage ('Ask for Version') {
            steps {
                script {
                    vDeployImage = params.vDeployImage
                    build = params.build
                    namespace = params.namespace
                    branch = params.branch
                    }
                }
            }
        stage ('Configure Ressources') {
            steps {
                withCredentials ( credentials ) {
                    configureRessources '${namespace}', "-f ${repo}/resources.yaml -p DB_SERVER=${env.DB_SERVER_TEST} -p GEO_DB_SERVER=${env.GEO_DB_SERVER_TEST} -p DB_PUB=${env.PUB_DB} -p DB_EDIT=${env.EDIT_DB} -p DB_OEREB=${env.OEREB_DB} -p DB_SOGIS=${env.SOGIS_DB} -p USER_OGC_SERVER=${DbUserOgcServer} -p PW_OGC_SERVER=${PwdOgcServer} -p NAMESPACE=${namespace}"
                    }
                }
            }
        stage ('Build new Image for qgis-server if necessary') {
            when {
                expression {
                    (build == 'ja')
                    }
                }
            steps {
                withCredentials ( credentials ) {
                    buildImage serviceName, repo, namespace, "-p BRANCH=${branch}", "--build-arg URL_PREFIX=/ows"
                    }
                }
            }
        stage ('Tag Image for qgis-server') {
            when {
                expression {
                    (build == 'ja')
                    }
                }    
            steps {
                tagImage serviceName, vDeployImage
                }
            }
        stage ('Deploy qgis-server in Test env') {
            steps {
                deployImage serviceName, namespace, vDeployImage, repo
                }
            }
        }
    }
