def serviceName = 'qgis-server'
def repo = 'https://raw.githubusercontent.com/sogis/pipelines/master/api_webgisclient/' + serviceName
def namespace = 'gdi-devel'
// NOTE, the "pipeline" directive/closure from the declarative pipeline syntax needs to include, or be nested outside,
// and "openshift" directive/closure from the OpenShift Client Plugin for Jenkins.  Otherwise, the declarative pipeline engine
// will not be fully engaged.
credentials = [
    usernamePassword(credentialsId: 'agi-apps-test-pw-ogc-server'          , usernameVariable: 'DbUserOgcServer'         , passwordVariable: 'PwdOgcServer'),
]
library identifier: 'jenkins-shared-libs@master', retriever: modernSCM(
    [$class: 'GitSCMSource',
     remote: 'https://github.com/sogis/jenkins-shared-libs.git'])

pipeline {
    agent any 
    options {
        // set a timeout of 10 minutes for this pipeline
        timeout(time: 10, unit: 'MINUTES')
        }
    parameters {
        string(defaultValue: "2.0.8",
               description: 'Bitte Version auswählen',
               name: 'version'
               )
        choice(choices: ['ja','nein'],
               description: 'Soll das Image gebaut werden?',
               name: 'build'     
               )
        }

    stages {
        stage ('Ask for Version') {
            steps {
                script {
                    version = params.version
                    build = params.build
                    println version
                    }
                }
            }
        stage ('Configure Ressources') {
            steps {
                withCredentials ( credentials ) {
                    configureRessources namespace, "-f ${repo}/ressources.yaml -p DB_SERVER=geodb-t.rootso.org -p PW_OGC_SERVER=${PwdOgcServer} -p GEO_DB_SERVER=geodb-t.verw.rootso.org -p NAMESPACE=${namespace}"
                    }
                }
            }
        stage ('Build new Image for qgis-server if necessary') {
            when {
                expression {
                    (build == 'ja')
                    }
                }
            steps {
                withCredentials ( credentials ) {
                    buildImage serviceName, repo, namespace, ""
                    }
                }
            }
        stage ('Tag Image for qgis-server') {
            when {
                expression {
                    (build == 'ja')
                    }
                }    
            steps {
                tagImage serviceName, version
                }
            }
        stage ('Deploy qgis-server in Test env') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject(namespace) {
                            def dcConfig = openshift.process( "${repo}/deploymentconfig.yaml", "-p", "NAMESPACE=${namespace}" )
                            deployImage serviceName, namespace, version, dcConfig
                            }
                        }
                    }
                }
            }
        }
    }
