def serviceName = 'qgis-server'
def configFileName = 'somap.json'
// NOTE, the "pipeline" directive/closure from the declarative pipeline syntax needs to include, or be nested outside,
// and "openshift" directive/closure from the OpenShift Client Plugin for Jenkins.  Otherwise, the declarative pipeline engine
// will not be fully engaged.
library identifier: "jenkins-shared-libs@${JENKINS_SHARED_LIBS_BRANCH}", retriever: modernSCM(
    [$class: 'GitSCMSource',
     remote: 'https://github.com/sogis/jenkins-shared-libs.git'])

pipeline {
    agent { label 'master' }
    options {
        // set a timeout of 10 minutes for this pipeline
        timeout(time: 35, unit: 'MINUTES')
        }
    parameters {
        string(description: 'Image Version',
               name: 'vBaseImage'
               )
        string(defaultValue: "master",
               description: 'Bitte Branch auswählen, der für die Pipeline verwendet werden soll',
               name: 'branch'
               )
        string(description: 'Anzahl der Replicas GetMap QGIS Server',
               defaultValue: '1',
               name: 'replicas'
               )
        string(defaultValue: "gdi-test",
               description: 'Bitte namespace auswählen',
               name: 'namespace'
               )
        }

    stages {
        stage ('Ask for Version') {
            steps {
                script {
                    repo = 'https://raw.githubusercontent.com/sogis/pipelines/' + params.branch + '/api_webgisclient/' + serviceName + '/deployment'
                    vBaseImage = params.vBaseImage
                    namespace = params.namespace
                    if ( namespace == 'gdi-test' ) { 
                      db_server = env.DB_SERVER_TEST
                      geo_db_server = env.GEO_DB_SERVER_TEST
                      environment = 'test'
                      sogisPicMirEnv = '-test'
                      replicas = '2'
                      resources = ['cpu_request': '0', 'cpu_limit': '4000m', 'memory_request': '0', 'memory_limit': '16384Mi']
                      }
                    else if ( namespace == 'gdi-integration' ) { 
                      db_server = env.DB_SERVER_INT
                      geo_db_server = env.GEO_DB_SERVER_TEST
                      environment = 'integration'
                      sogisPicMirEnv = '-int'
                      replicas = '2'
                      resources = ['cpu_request': '500m', 'cpu_limit': '4000m', 'memory_request': '2048Mi', 'memory_limit': '8192Mi']
                      }
                    else if ( namespace == 'gdi-production' ) { 
                      db_server = env.DB_SERVER_PROD
                      geo_db_server = env.GEO_DB_SERVER_PROD
                      environment = 'production'
                      sogisPicMirEnv = '-prod'
                      replicas = '6'
                      resources = ['cpu_request': '1500m', 'cpu_limit': '4000m', 'memory_request': '4096Mi', 'memory_limit': '16384Mi']
                      }
                    else {
                      environment = 'test'
                      sogisPicMirEnv = '-test'
                      replicas = '2'
                      resources = ['cpu_request': '0', 'cpu_limit': '0', 'memory_request': '0', 'memory_limit': '0']
                      }
                    buildNumber = BUILD_NUMBER
                    jobName = JOB_NAME
                    credentials = [ 
                        usernamePassword(credentialsId: (env.NAMESPACE_JENKINS) + '-jenkins-dbuser-ogc-server-secret'   , usernameVariable: 'DbUserOgcServer'   , passwordVariable: 'PwdOgcServer'),
                        usernamePassword(credentialsId: (env.NAMESPACE_JENKINS) + '-jenkins-dbuser-sogis-service-secret', usernameVariable: 'DbUserSogisService', passwordVariable: 'PwdSogisService')
                        ]
                    }
                }
            }
        stage ('Configure Ressources') {
            steps {
                withCredentials ( credentials ) {
                    configureRessources '${namespace}', "-f ${repo}/resources.yaml -p DB_SERVER=${db_server} -p GEO_DB_SERVER=${geo_db_server} -p DB_PUB=${env.PUB_DB} -p DB_EDIT=${env.EDIT_DB} -p DB_OEREB=${env.OEREB_DB} -p DB_SOGIS=${env.SOGIS_DB} -p USER_OGC_SERVER=${DbUserOgcServer} -p PW_OGC_SERVER=${PwdOgcServer}"
                    }
                }
            }
        stage ('Create configs') {
            steps {
                withCredentials ( credentials ) {
                    createConfigs namespace, branch, DbUserSogisService, PwdSogisService, db_server, env.SIMI_DB, configFileName, serviceName, 'wms-qgs-content', 'sogis', 'json2qgs'
                    createConfigs namespace, branch, DbUserSogisService, PwdSogisService, db_server, env.SIMI_DB, 'somap_wfs.json', serviceName, 'wfs-qgs-content', 'sogis', 'json2qgs'
                    createConfigs namespace, branch, DbUserSogisService, PwdSogisService, db_server, env.SIMI_DB, 'somap_print.json', serviceName, 'print-qgs-content', 'sogis', 'json2qgs'
                    }
                }
            }
        stage ('Create qgs files') {
            agent { 
              kubernetes {
                label 'json2qgs-agent'
                defaultContainer 'jnlp'
                idleMinutes '600'
                yaml """
                  apiVersion: v1
                  kind: Pod
                  metadata:
                    labels:
                      jenkins: slave
                      jenkins/label: json2qgs-agent
                    name: json2qgs-agent
                  spec:
                    containers:
                    - args:
                      - "********"
                      image: "quay.io/openshift/origin-jenkins-agent-base:4.10"
                      imagePullPolicy: "IfNotPresent"
                      name: "jnlp"
                      env:
                      - name: "LC_ALL"
                        value: "C.UTF-8"
                      resources:
                        limits:
                          memory: "2Gi"
                          cpu: "1"
                        requests:
                          memory: "1Gi"
                          cpu: "250m"
                      tty: false
                      volumeMounts:
                      - mountPath: "/qgs-resources"
                        name: "volume-0"
                        readOnly: false
                      - mountPath: "/tmp"
                        name: "workspace-volume"
                        readOnly: false
                      workingDir: "/tmp"
                    - args:
                      - "24h"
                      command:
                      - "sleep"
                      image: "sogis/json2qgs:v1.0.6"
                      imagePullPolicy: "IfNotPresent"
                      name: "json2qgs"
                      resources:
                        limits:
                          memory: "2Gi"
                          cpu: "1"
                        requests:
                          memory: "1Gi"
                          cpu: "200m"
                      tty: false
                      volumeMounts:
                      - mountPath: "/qgs-resources"
                        name: "volume-0"
                        readOnly: false
                      - mountPath: "/tmp"
                        name: "workspace-volume"
                        readOnly: false
                      workingDir: "/tmp"
                    restartPolicy: "Never"
                    serviceAccountName: "jenkins"
                    volumes:
                    - name: "volume-0"
                      persistentVolumeClaim:
                        claimName: "qgs-resources-claim"
                        readOnly: false
                    - emptyDir:
                        medium: ""
                      name: "workspace-volume"
                  """
                  }
             }
            steps {
                container('json2qgs') {
                    dir('qgs') {
                      unstash name: configFileName
                      unstash name: 'somap_wfs.json'
                      unstash name: 'somap_print.json'
                    }
                    sh """
                        if [ ! -d "/tmp/config/default" ]; then
                          mkdir -p /tmp/config/default
                        fi
                        python3 /srv/json2qgs/json2qgs.py qgs/somap.json wms /tmp/config/default 3 --qgsName somap --qgsTemplateDir /srv/json2qgs/qgs
                        python3 /srv/json2qgs/json2qgs.py qgs/somap_print.json wms /tmp/config/default 3 --qgsName somap_print --qgsTemplateDir /srv/json2qgs/qgs
                        python3 /srv/json2qgs/json2qgs.py qgs/somap_wfs.json wfs /tmp/config/default 3 --qgsName somap_wfs --qgsTemplateDir /srv/json2qgs/qgs
                    """
                    }
                script {
                    PODNAME= sh([script: 'oc get pods -o custom-columns=POD:.metadata.name --no-headers -n ${namespace} | grep qgis-server | grep -v -E -m 1 "featureinfo|build|print|deploy"', returnStdout: true]).trim()
                    sh """
                        oc rsync -n ${namespace} /tmp/config/default/ $PODNAME:/data
                        oc rsync -n ${namespace} /tmp/qwc2/assets/forms/autogen/ $PODNAME:/qwc-assets/forms/autogen
                    """
                    }
                dir('/tmp/config/default') {
                    archiveArtifacts artifacts: '**', onlyIfSuccessful: true, allowEmptyArchive: true
                    }
                dir('/tmp/qwc2/assets/forms/autogen') {
                    archiveArtifacts artifacts: '**', onlyIfSuccessful: true, allowEmptyArchive: true
                    }
                }
            post {
                always {
                    sh """
                        rm -rf $env.WORKSPACE/config $env.WORKSPACE/qgs
                    """
                    }
                }
            }
        stage ('Deploy qgis-server') {
            steps {
                deployImage serviceName, namespace, vBaseImage, repo, replicas, resources['cpu_request'], resources['cpu_limit'], resources['memory_request'], resources['memory_limit'], "-p ENVIRONMENT=${sogisPicMirEnv}"
                }
            }
        }
    post {
        // Clean after build
        cleanup {
            sh """
                rm -rf $JENKINS_HOME/jobs/$JOB_NAME/workspace\\@script
                rm -rf $JENKINS_HOME/jobs/$JOB_NAME/workspace\\@libs
                rm -rf $WORKSPACE/*
            """
            }
        }
    }
