apiVersion: v1
kind: Template
metadata:
  name: ressources-qgis-server
  annotations:
    description: >-
      "Creates necessary ressources for qgis-server"
parameters:
  - description: DB Server Url
    name: DB_SERVER
    value:
  - description: Password DB User ogc_server
    name: PW_OGC_SERVER
    value: password
  - description: Geo DB Server
    name: GEO_DB_SERVER
    value:
  - description: Namespace
    name: NAMESPACE
    value: gdi-devel
objects:
- apiVersion: v1
  stringData:
    pg_service.conf: |
      [sogis_webmapping]
      host=${DB_SERVER}
      port=5432
      dbname=pub
      user=ogc_server
      password=${PW_OGC_SERVER}
      sslmode=require

      [sogis_geodb]
      host=${GEO_DB_SERVER}
      port=5432
      dbname=sogis
      user=mspublic
      sslmode=disable

      [sogis_edit]
      host=${DB_SERVER}
      port=5432
      dbname=edit
      user=ogc_server
      password=${PW_OGC_SERVER}
      sslmode=require

      [sogis_oereb]
      host=${DB_SERVER}
      port=5432
      dbname=oereb
      user=ogc_server
      password=${PW_OGC_SERVER}
      sslmode=require
  kind: Secret
  metadata:
    labels:
      application: gdi
    name: qgis-server-pg-config
    namespace: ${NAMESPACE}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: qgis-server
    labels:
      application: gdi
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/${NAMESPACE}/qgis-server:latest
      name: latest
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose --file docker-compose-4openshift.yml --provider openshift
        up
    labels:
      app: qgis-server
    name: qgis-server
  spec:
    ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: qgis-server
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: qgs-resources-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: nfs
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: datensogispicmir-claim1
  spec:
    accessModes:
    - ReadOnlyMany
    resources:
      requests:
        storage: 5Gi
    storageClassName: nfs
