apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ressources-ogc-service
  annotations:
    description: >-
      "Creates necessary ressources for ogc-service"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: ogc-service
      app: gdi 
    name: ogc-service
  spec:
    ports:
    - name: "80"
      port: 80
      protocol: TCP 
      targetPort: 9090
    selector:
      service: ogc-service
