apiVersion: v1
kind: Template
metadata:
  name: document-service
  annotations:
    description: "Creates deploymentConfig for document-service"
parameters:
  - description: Openshift Namespace
    name: NAMESPACE
    value:
  - description: "Image Stream Tag"
    name: TAG
    value:
labels:
  application: gdi
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kompose.cmd: kompose --file docker-compose-4openshift.yml --provider openshift
        convert
      kompose.version: 1.10.0 (8bb0907)
    generation: 1
    labels:
      service: document-service
      app: gdi
    name: document-service
  spec:
    replicas: 2
    selector:
      service: document-service
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 120
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: document-service
          app: gdi
      spec:
        containers:
        - env:
          - name: JASPER_SERVICE_URL
            value: http://jasper-reporting-service.${NAMESPACE}.svc/reports
          - name: PERMISSION_SERVICE_URL
            value: http://permission-service.${NAMESPACE}.svc
          - name: JWT_SECRET_KEY
            value: fce9dd0cc67ae26c7b2fb912e31a4657e99014e50ccb90bd
          - name: ALLOW_BASIC_AUTH_USER
            value: "True"
          - name: JASPER_TIMEOUT
            value: "1200"
          - name: CONFIG_PATH
            value: /srv/qwc_service/config
          - name: SERVICE_MOUNTPOINT
            value: /api/v1/document
          image: docker-registry.default.svc:5000/${NAMESPACE}/document-service:${TAG}
          imagePullPolicy: IfNotPresent
          name: sogis-document-service
          ports:
          - containerPort: 9090
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/www
            name: wsgi-service-config-claim
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - secret:
            items:
            - key: pg_service.conf
              path: .pg_service.conf
            secretName: wsgi-service-pg-config
          name: wsgi-service-config-claim
    triggers: []
