def serviceName = env.JOB_BASE_NAME
def environment = params.namespace.substring(params.namespace.lastIndexOf('-') + 1)
// NOTE, the "pipeline" directive/closure from the declarative pipeline syntax needs to include, or be nested outside,
// and "openshift" directive/closure from the OpenShift Client Plugin for Jenkins.  Otherwise, the declarative pipeline engine
// will not be fully engaged.
library identifier: "jenkins-shared-libs@${JENKINS_SHARED_LIBS_BRANCH}", retriever: modernSCM(
    [$class: 'GitSCMSource',
     remote: 'https://github.com/sogis/jenkins-shared-libs.git'])

pipeline {
    agent { label 'master' } 
    options {
        // set a timeout of 10 minutes for this pipeline
        timeout(time: 10, unit: 'MINUTES')
        }
    parameters {
        string(defaultValue: "master",
               description: 'Bitte Branch auswählen, der für die Pipeline verwendet werden soll',
               name: 'branch'
               )
        string(defaultValue: "gdi-test",
               description: 'Bitte namespace auswählen',
               name: 'namespace'
               )
        }

    stages {
        stage ('Ask for Version') {
            steps {
                script {
                    repo = 'https://raw.githubusercontent.com/sogis/pipelines/' + params.branch + '/api_webgisclient/' + serviceName + '/deployment'
                    branch = params.branch
                    namespace = params.namespace
                    if ( namespace == 'gdi-test' ) {
                      db_server = env.DB_SERVER_TEST
                      }
                    else if ( namespace == 'gdi-integration' ) {
                      db_server = env.DB_SERVER_INT
                      }
                    else if ( namespace == 'gdi-production' ) {
                      db_server = env.DB_SERVER_PROD
                      }
                    else {
                      db_server = env.DB_SERVER_PROD
                      }
                    if (params.containsKey("configs")) {
                        buildNumber = params.buildNumber
                        jobName = params.jobName
                        }
                    else {
                        buildNumber = BUILD_NUMBER
                        jobName = JOB_NAME
                        }
                    credentials = [
                        usernamePassword(credentialsId: (env.OPENSHIFT_ENVIRONMENT) + '-jenkins-dbuser-sogis-service-secret'       , usernameVariable: 'DbUserSogisService'      , passwordVariable: 'PwdSogisService')
                        ]
                    }
                }
            }
        stage ('Configure Ressources') {
            steps {
                configureRessources serviceName, namespace, repo, environment
                }
            }
        stage ('Create configs') {
            steps {
                withCredentials ( credentials ) {
                    createConfigs namespace, branch, DbUserSogisService, PwdSogisService, db_server, env.SIMI_DB, 'samlAuthConfig.json', serviceName, 'saml-auth', 'qwc', 'sogis-config-generator'
                    }
                }
            }
        stage ('Deploy auth-service in Test env') {
            steps {
                deployImage serviceName, namespace, repo, environment
                }
            }
        }
    post {
        // Clean after build
        cleanup {
            sh """
                rm -rf $JENKINS_HOME/jobs/$JOB_NAME/workspace\\@script
                rm -rf $JENKINS_HOME/jobs/$JOB_NAME/workspace\\@libs
                rm -rf $WORKSPACE/*
            """
            }
        }
    }
