apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: resources-permalink-service
  annotations:
    description: >-
      "Creates necessary resources for permalink-service"
parameters:
  - description: DB Server Url
    name: DB_SERVER
  - description: Edit DB
    name: DB_EDIT
  - description: DB User sogis_service_write
    name: USER_SOGIS_SERVICE_WRITE
  - description: Password DB User sogis_service_write
    name: PW_SOGIS_SERVICE_WRITE
objects:
- apiVersion: v1
  stringData:
    pg_service.conf: |
      [sogis_edit_write]
      host=${DB_SERVER}
      port=5432
      dbname=${DB_EDIT}
      user=${USER_SOGIS_SERVICE_WRITE}
      password=${PW_SOGIS_SERVICE_WRITE}
      sslmode=require
  kind: Secret
  metadata:
    labels:
      app: permalink-service
    name: permalink-service-pg-service-secret
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: permalink-service
      app: gdi 
    name: permalink-service
  spec:
    ports:
    - name: "80"
      port: 80
      protocol: TCP 
      targetPort: 9090
    selector:
      service: permalink-service
