apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ressources-search-service
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: search-service
      app: gdi
    name: search-service
  spec:
    ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 9090
    selector:
      service: search-service
    sessionAffinity: None
    type: ClusterIP
