apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ressources-print-service
  annotations:
    description: >-
      "Creates necessary ressources for print-service"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: print-service
      app: gdi
    name: print-service
  spec:
    ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 9090
    selector:
      service: print-service
