apiVersion: v1
kind: Template
metadata:
  name: build-elevation-service
  annotations:
    openshift.io/display-name: "Buildconfig for elevation-service"
    description: >-
      "Creates BuildConfig for elevation-service"
parameters:
  - description: tag of base image
    name: BASETAG
  - description: tag of deploy image
    name: DEPLOYTAG
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      service: elevation-service
      app: gdi
    name: elevation-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: elevation-service:${DEPLOYTAG}
    source:
      contextDir: elevation-service
      git:
        ref: master
        uri: https://github.com/sogis/qwc_services.git
      type: Git
    strategy:
      dockerStrategy:
        buildArgs:
        - name: SERVICE
          value:
        - name: SERVICE_PACKAGES
          value:
        from:
          kind: DockerImage
          name: sourcepole/qwc-elevation-service:${BASETAG}
        noCache: true
      type: Docker
    resources:
      limits:
        cpu: "1000m"
        memory: "4096Mi"
      requests:
        cpu: "250m"
        memory: "1024Mi"
