apiVersion: v1
kind: Template
metadata:
  name: elevation-service
  annotations:
    description: "Creates deploymentConfig for elevation-service"
parameters:
  - description: Openshift Namespace
    name: NAMESPACE
    value:
labels:
  application: gdi
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      io.kompose.service: elevation-service
    name: elevation-service
  spec:
    replicas: 2
    selector:
      io.kompose.service: elevation-service
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 120
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: elevation-service
      spec:
        containers:
        - env:
          - name: ELEVATION_DATASET
            value: /data/daten_aktuell/agi/hoehenmodelle/lidar/2014/dtm/50cm/lidar_2014_dtm_50cm.vrt
          image: docker-registry.default.svc:5000/${NAMESPACE}/elevation-service
          imagePullPolicy: IfNotPresent
          name: sogis-elevation-service
          ports:
          - containerPort: 9090
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /data
            name: datensogispicmir
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: datensogispicmir
          persistentVolumeClaim:
            claimName: datensogispicmir-claim1
            readOnly: true
    test: false
    triggers:
    - type: ConfigChange
