apiVersion: v1
kind: Template
metadata:
  name: elevation-service
  annotations:
    description: "Creates deploymentConfig for elevation-service"
parameters:
  - description: Openshift Namespace
    name: NAMESPACE
  - description: "Image Stream Tag"
    name: TAG
  - description: Environment
    name: ENVIRONMENT
  - description: Number of Replicas
    name: REPLICAS
  - description: cpu request
    name: CPU_REQUEST
  - description: cpu limit
    name: CPU_LIMIT
  - description: Memory Request
    name: MEMORY_REQUEST
  - description: Memory Limit
    name: MEMORY_LIMIT
labels:
  app: gdi
  service: elevation-service
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: elevation-service
      app: gdi
    name: elevation-service
  spec:
    replicas: ${{REPLICAS}}
    selector:
      service: elevation-service
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 120
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          service: elevation-service
          app: gdi
      spec:
        containers:
        - env:
          - name: CONFIG_PATH
            value: "/srv/qwc_service/config"
          image: docker-registry.default.svc:5000/${NAMESPACE}/elevation-service:${TAG}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: healthz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: sogis-elevation-service
          ports:
          - containerPort: 9090
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: ready
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /data
            name: datensogispicmir
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: datensogispicmir
          persistentVolumeClaim:
            claimName: datensogispicmir-claim${ENVIRONMENT}
            readOnly: true
    test: false
    triggers: []
