def serviceName = 'elevation-service'
def configFileName = 'elevationConfig.json'
// NOTE, the "pipeline" directive/closure from the declarative pipeline syntax needs to include, or be nested outside,
// and "openshift" directive/closure from the OpenShift Client Plugin for Jenkins.  Otherwise, the declarative pipeline engine
// will not be fully engaged.
library identifier: "jenkins-shared-libs@${JENKINS_SHARED_LIBS_BRANCH}", retriever: modernSCM(
    [$class: 'GitSCMSource',
     remote: 'https://github.com/sogis/jenkins-shared-libs.git'])

pipeline {
    agent { label 'master' } 
    options {
        // set a timeout of 10 minutes for this pipeline
        timeout(time: 10, unit: 'MINUTES')
        }
    parameters {
        string(defaultValue: "latest",
               description: 'Basis Image Version',
               name: 'vBaseImage'
               )
        string(description: 'Tag des generierten bzw. des deployten Images',
               name: 'vDeployImage'
              )
        string(defaultValue: "master",
               description: 'Bitte Branch auswählen, der für die Pipeline verwendet werden soll',
               name: 'branch'
               )
        string(description: 'Anzahl der Replicas',
               defaultValue: '1',
               name: 'replicas'
               )
        string(defaultValue: "gdi-test",
               description: 'Bitte Namespace auswählen',
               name: 'namespace'
              )
        choice(choices: ['ja','nein'],
               description: 'Soll das Image gebaut werden?',
               name: 'build'     
               )
        }

    stages {
        stage ('Ask for Version') {
            steps {
                script {
                    repo = 'https://raw.githubusercontent.com/sogis/pipelines/' + params.branch + '/api_webgisclient/' + serviceName
                    vBaseImage = params.vBaseImage
                    vDeployImage = params.vDeployImage
                    replicas = params.replicas
                    branch = params.branch
                    build = params.build
                    namespace = params.namespace
                    if ( namespace == 'gdi-test' ) { 
                      db_server = env.DB_SERVER_TEST
                      geo_db_server = env.GEO_DB_SERVER_TEST
                      environment = 'test'
                      sogisPicMirEnv = '-test'
                      resources = ['cpu_request': '0', 'cpu_limit': '0', 'memory_request': '0', 'memory_limit': '0']
                      }
                    else if ( namespace == 'gdi-integration' ) { 
                      db_server = env.DB_SERVER_INT
                      geo_db_server = env.GEO_DB_SERVER_TEST
                      environment = 'integration'
                      sogisPicMirEnv = '-int'
                      resources = ['cpu_request': '6m', 'cpu_limit': '600m', 'memory_request': '70Mi', 'memory_limit': '140Mi']
                      }
                    else if ( namespace == 'gdi' ) { 
                      db_server = env.DB_SERVER_PROD
                      geo_db_server = env.GEO_DB_SERVER_PROD
                      environment = 'production'
                      sogisPicMirEnv = '1'
                      resources = ['cpu_request': '6m', 'cpu_limit': '600m', 'memory_request': '140Mi', 'memory_limit': '140Mi']
                      }
                    else {
                      environment = 'test'
                      sogisPicMirEnv = '-test'
                      resources = ['cpu_request': '0', 'cpu_limit': '0', 'memory_request': '0', 'memory_limit': '0']
                      }
                    if (params.containsKey("configs")) {
                        buildNumber = params.buildNumber
                        jobName = params.jobName
                        }
                    else {
                        buildNumber = BUILD_NUMBER
                        jobName = JOB_NAME
                        }
                     credentials = [ 
                        usernamePassword(credentialsId: 'jenkinsApi', usernameVariable: 'apiUser', passwordVariable: 'PwdApiUser')
                        ]
                    }
                }
            }
        stage ('Configure Ressources') {
            steps {
                configureRessources '${namespace}', " -f ${repo}/resources.yaml -p NAMESPACE=${namespace} "
                }
            }
        stage ('Create configs') {
            when {
               beforeAgent true
               expression {
                   (params.configs != true)
                   }
               }
            agent { label 'config-generator-agent' }
            steps {
                createConfigs([:])
                }
            }
        stage ('Build new Image for elevation-service if necessary') {
            when {
                expression {
                    (build == 'ja')
                    }
                }
            steps {
                withCredentials ( credentials ) {
                    buildImage serviceName, repo, namespace, "-p BASETAG=${vBaseImage} -p DEPLOYTAG=${vDeployImage}", configFileName, jobName, buildNumber, "--build-arg SERVICE=elevation --build-arg SERVICE_PACKAGES=python3-gdal"
                    }
                }
            }
        stage ('Deploy elevation-service in Test env') {
            steps {
                deployImage serviceName, namespace, vDeployImage, repo, replicas, resources['cpu_request'], resources['cpu_limit'], resources['memory_request'], resources['memory_limit'], "-p ENVIRONMENT=${sogisPicMirEnv}"
                }
            }
        }
    }
