apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ressources-elevation-service
  annotations:
    description: >-
      "Creates necessary ressources for elevation-service"
parameters:
  - description: Namespace
    name: NAMESPACE
    value: gdi-devel
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: elevation-service
    labels:
      app: gdi
      service: elevation-service
  spec:
    tags:
    - from:
        kind: DockerImage
        name: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/elevation-service:latest
      name: latest
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose --file docker-compose-4openshift.yml --provider openshift
        up
      kompose.version: 1.10.0 (8bb0907)
    labels:
      service: elevation-service
      app: gdi 
    name: elevation-service
  spec:
    ports:
    - name: "80"
      port: 80
      protocol: TCP 
      targetPort: 9090
    selector:
      service: elevation-service
    sessionAffinity: None
    type: ClusterIP
