@startuml

package "QGIS Server" {
    package "WFS" {
        [wfs_layers.sql]
    
    }
    
    package "WMS" {
        [root_layers.sql]
        [wms.sql]
        [wms_print.sql]
        

        [trafo_wms_layer_v]
        [trafo_wms_pg_table_v]
        [trafo_wms_tableview_attribute_v]
        [trafo_wms_dp_common_v]
        [trafo_wms_outtypes_v]
        [trafo_wms_rootlayer_v]
        
        root_layers.sql --> trafo_wms_rootlayer_v
        
        wms.sql --> trafo_wms_layer_v
        wms_print.sql --> trafo_wms_layer_v
        
        trafo_wms_layer_v --> trafo_wms_pg_table_v
        trafo_wms_layer_v --> trafo_wms_tableview_attribute_v
        trafo_wms_layer_v --> trafo_wms_dp_common_v
        trafo_wms_layer_v --> trafo_wms_outtypes_v
    }
}

@enduml