apiVersion: v1
kind: Template
metadata:
  name: build-permission-service
  annotations:
    openshift.io/display-name: "Buildconfig for permission-service"
    description: >-
      "Creates BuildConfig for permission-service"
parameters:
  - description: branch to build
    name: BRANCH
    value:
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      service: permission-service
      app: gdi
    name: permission-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: permission-service:latest
    source:
      contextDir: docker/wsgi-service
      git:
        ref: ${BRANCH}
        uri: https://git.sourcepole.ch/ktso/somap.git
      sourceSecret:
        name: deployso-at-gitlab
      type: Git
    strategy:
      dockerStrategy:
        buildArgs:
        - name: GIT_VERSION
          value: v2.0.8
        - name: SERVICE
          value:   
        env:
        - name: GIT_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: deployso-at-gitlab
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: deployso-at-gitlab
        from:
          kind: DockerImage
          name: ubuntu:16.04
      type: Docker
