apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qgs-resources-claim-iscsi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: iscsi
status: {}
