apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: featureinfo-service
  annotations:
    description: "Creates deploymentConfig for featureinfo-service"
parameters:
  - description: Openshift Namespace
    name: NAMESPACE
  - description: Application Environment
    name: ENVIRONMENT
  - description: "Image Stream Tag"
    name: TAG
  - description: Number of Replicas
    name: REPLICAS
  - description: cpu request
    name: CPU_REQUEST
  - description: cpu limit
    name: CPU_LIMIT
  - description: Memory Request
    name: MEMORY_REQUEST
  - description: Memory Limit
    name: MEMORY_LIMIT
labels:
  application: gdi
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kompose.cmd: kompose --file docker-compose-4openshift.yml --provider openshift
        convert
      kompose.version: 1.10.0 (8bb0907)
    labels:
      service: featureinfo-service
      app: gdi
    name: featureinfo-service
  spec:
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 1
    selector:
      service: featureinfo-service
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 120
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          service: featureinfo-service
          app: gdi
      spec:
        containers:
        - env:
          - name: DEFAULT_QGIS_SERVER_URL
            value: http://qgis-server-featureinfo.${NAMESPACE}.svc/ows/
          - name: JWT_SECRET_KEY
            value: fce9dd0cc67ae26c7b2fb912e31a4657e99014e50ccb90bd
          - name: ALLOW_BASIC_AUTH_USER
            value: "True"
          - name: HEATDRILL_SERVICE_URL
            value: http://heatdrill-service.agi-apps-${ENVIRONMENT}/service
          - name: SERVICE_MOUNTPOINT
            value: /api/v1/featureinfo
          - name: CONFIG_PATH
            value: /srv/qwc_service/config
          - name: USE_PERMISSION_ATTRIBUTE_ORDER
            value: "True"
          - name: SERVICE_UID
            value: www-data
          - name: SERVICE_GID
            value: www-data
          - name: PGSERVICEFILE
            value: /usr/etc/postgresql/pg_service.conf
          - name: TENANT_HEADER
            value: Tenant
          - name: TENANT_PATH_PREFIX
            value: "@service_prefix@"
          image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/featureinfo-service:${TAG}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: healthz
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: sogis-featureinfo-service
          ports:
          - containerPort: 9090
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: ready
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /usr/etc/postgresql
            name: featureinfo-service-config-claim
          - mountPath: /srv/qwc_service/config
            name: qgs-resources
            subPath: config
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - secret:
            items:
            - key: pg_service.conf
              path: pg_service.conf
            secretName: featureinfo-service-pg-service-secret
          name: featureinfo-service-config-claim
        - name: qgs-resources
          persistentVolumeClaim:
              claimName: qgs-resources-claim
              readOnly: true
    test: false
    triggers: []
