apiVersion: v1
kind: Template
metadata:
  name: ccc-config-service
  annotations:
    description: "Creates deploymentConfig for ccc-config-service"
parameters:
  - description: Openshift Namespace
    name: NAMESPACE
  - description: Image Stream Tag
    name: TAG
  - description: Base Url of AGI GDI
    name: BASEURL
labels:
  application: gdi
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    generation: 1
    labels:
      service: ccc-config-service
      app: gdi
    name: ccc-config-service
  spec:
    replicas: 2
    selector:
      service: ccc-config-service
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 10%
        maxUnavailable: 10%
        timeoutSeconds: 120
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        labels:
          service: ccc-config-service
          app: gdi
      spec:
        containers:
          - env:
            - name: CCC_ZOOMTO_DATA_SERVICE_URL
              value: 'http://data-service.${NAMESPACE}.svc'
            - name: CONFIG_PATH
              value: "/srv/qwc_service/config"
            - name: SERVICE_MOUNTPOINT
              value: "/api/v1/ccc"
            image: >-
              docker-registry.default.svc:5000/${NAMESPACE}/ccc-config-service:${TAG}
            imagePullPolicy: Always
            name: sogis-ccc-config-service
            resources: {}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
