apiVersion: v1
kind: Template
metadata:
  name: ressources-ccc-config-service
  annotations:
    description: >-
      "Creates necessary ressources for ccc-config-service"
parameters:
  - description: Namespace
    name: NAMESPACE
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ccc-config-service
    labels:
      app: gdi
      service: ccc-config-service
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/${NAMESPACE}/ccc-config-service:latest
      name: latest
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose --file docker-compose-4openshift.yml --provider openshift
        up
      kompose.version: 1.10.0 (8bb0907)
    labels:
      service: ccc-config-service
      app: gdi
    name: ccc-config-service
  spec:
    ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 9090
    selector:
      service: ccc-config-service
    sessionAffinity: None
    type: ClusterIP
