apiVersion: v1
kind: Template
metadata:
  name: ressources-qgis-server-featureinfo
  annotations:
    description: >-
      "Creates necessary ressources for qgis-server"
parameters:
  - description: DB Server Url
    name: DB_SERVER
    value:
  - description: Geo DB Server
    name: GEO_DB_SERVER
    value:
  - description: Pub DB
    name: DB_PUB
    value:
  - description: Edit DB
    name: DB_EDIT
    value:
  - description: Oereb DB
    name: DB_OEREB
    value:
  - description: Sogis DB
    name: DB_SOGIS
    value:
  - description: DB User ogc_server
    name: USER_OGC_SERVER
    value:
  - description: Password DB User ogc_server
    name: PW_OGC_SERVER
    value:
  - description: Namespace
    name: NAMESPACE
    value:
objects:
- apiVersion: v1
  stringData:
    pg_service.conf: |
      [sogis_webmapping]
      host=${DB_SERVER}
      port=5432
      dbname=${DB_PUB}
      user=${USER_OGC_SERVER}
      password=${PW_OGC_SERVER}
      sslmode=require

      [sogis_geodb]
      host=${GEO_DB_SERVER}
      port=5432
      dbname=${DB_SOGIS}
      user=mspublic
      sslmode=disable

      [sogis_edit]
      host=${DB_SERVER}
      port=5432
      dbname=${DB_EDIT}
      user=${USER_OGC_SERVER}
      password=${PW_OGC_SERVER}
      sslmode=require

      [sogis_oereb]
      host=${DB_SERVER}
      port=5432
      dbname=${DB_OEREB}
      user=${USER_OGC_SERVER}
      password=${PW_OGC_SERVER}
      sslmode=require
  kind: Secret
  metadata:
    labels:
      app: gdi
      service: qgis-server
    name: qgis-server-pg-config
    namespace: ${NAMESPACE}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: qgis-server
    labels:
      app: gdi
      service: qgis-server
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/${NAMESPACE}/qgis-server:latest
      name: latest
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: qgis-server
      service: qgis-server-featureinfo
      app: gdi
    name: qgis-server-featureinfo
  spec:
    ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      service: qgis-server-featureinfo
