apiVersion: v1
kind: Template
metadata:
  name: build-featureinfo-service
  annotations:
    openshift.io/display-name: "Buildconfig for featureinfo-service"
    description: >-
      "Creates BuildConfig for featureinfo-service"
parameters:
  - description: tag of base image
    name: BASETAG
  - description: tag of deploy image
    name: DEPLOYTAG
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      service: featureinfo-service
      app: gdi
    name: featureinfo-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: featureinfo-service:${DEPLOYTAG}
    source:
      contextDir: featureinfo-service
      git:
        ref: master
        uri: https://github.com/sogis/qwc_service.git
      sourceSecret:
        name: deployso-at-gitlab
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: sourcepole/qwc-feature-info-service:${BASETAG}
      type: Docker
