apiVersion: v1
kind: Template
metadata:
  name: build-data-service
  annotations:
    openshift.io/display-name: "Buildconfig for data-service"
    description: >-
      "Creates BuildConfig for data-service"
parameters:
  - description: branch to build
    name: BRANCH
  - description: tag of image
    name: TAG
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      service: data-service
      app: gdi
    name: data-service
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: data-service:${TAG}
    source:
      contextDir: data-service
      git:
        ref: master
        uri: https://github.com/sogis/qwc_services.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: sourcepole/qwc-data-service:${TAG}
      type: Docker
