apiVersion: v1
kind: Template
metadata:
  name: build-print-service
  annotations:
    openshift.io/display-name: "Buildconfig for print-service"
    description: >-
      "Creates BuildConfig for print-service"
parameters:
  - description: tag of baseimage
    name: BASETAG
  - description: tag of deploy image
    name: DEPLOYTAG
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      service: print-service
      app: gdi
    name: print-service
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: print-service:${DEPLOYTAG}
    source:
      contextDir: print-service
      git:
        ref: master
        uri: https://github.com/sogis/qwc_services.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: sourcepole/qwc-print-service:${BASETAG}
      type: Docker
